import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;

public class Order extends javax.swing.JFrame {  
    public static int countCart;  
    public static String[] sizeSelection = new String[50];    
    /*
    1 - 6 Inch
    2 - 12 Inch
    */
    public static String[] breadSelection = new String[50];
    /*
    1 - Wheat
    2 - Honey Oat
    3 - Italian Bread Loaf
    4 - Parmesan
    */
    public static String[] flavourSelection = new String[50];
    /*
    1 - Chicken Slice
    2 - Roast Beef
    3 - Steak & Cheese
    4 - Tuna
    5 - Turkey Breast
    6 - Veggie Delite
    */        
    /*
    Veggie
    1 - Tomato
    2 - Onion
    3 - Cucumber
    4 - Olive
    5 - Green Pepper
    6 - Lettuce
    */    
    /*
    Sauce
    1 - Chili Sauce
    2 - Mayonnaise
    3 - Ketchup
    4 - Thousand Island
    */
    public static String[] addonSelection = new String[50];
    /*
    1 - Set 1
    2 - Set 2
    3 - Set 3
    4 - Set 4
    5 - Ala Carte
    */    
    public static double[] price = new double[50];
    DecimalFormat df = new DecimalFormat("0.00");
    public static ImageIcon[] pictureTop = new ImageIcon[50];
    public static ImageIcon[] pictureBottom = new ImageIcon[50];
    public Order() {
        initComponents();
        icon();
        closeMenu();
        allVarInit();    
        cart.setText("Item(s) in cart: "+countCart);
        defaultInstruction();
        buttonDone.setVisible(false);      
        viewCart.setVisible(false);     
        clearCart.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundColour = new javax.swing.JPanel();
        buttonDone = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        panelSelection = new javax.swing.JPanel();
        size = new javax.swing.JButton();
        bread = new javax.swing.JButton();
        flavour = new javax.swing.JButton();
        veggie = new javax.swing.JButton();
        sos = new javax.swing.JButton();
        addon = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        veggiePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        exitVegie = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        RBveggie1 = new javax.swing.JRadioButton();
        RBveggie2 = new javax.swing.JRadioButton();
        RBveggie3 = new javax.swing.JRadioButton();
        RBveggie4 = new javax.swing.JRadioButton();
        RBveggie5 = new javax.swing.JRadioButton();
        RBveggie6 = new javax.swing.JRadioButton();
        sizePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        exitSize = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        RBsize1 = new javax.swing.JCheckBox();
        RBsize2 = new javax.swing.JCheckBox();
        breadPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exitBread = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        RBbread1 = new javax.swing.JCheckBox();
        RBbread2 = new javax.swing.JCheckBox();
        RBbread3 = new javax.swing.JCheckBox();
        RBbread4 = new javax.swing.JCheckBox();
        addonPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        RBaddon4 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        RBaddon3 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        exitAddon = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        RBaddon1 = new javax.swing.JCheckBox();
        RBaddon2 = new javax.swing.JCheckBox();
        RBaddon5 = new javax.swing.JCheckBox();
        flavourPanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RBflavour2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RBflavour5 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exitFlavour = new javax.swing.JButton();
        RBflavour1 = new javax.swing.JCheckBox();
        RBflavour3 = new javax.swing.JCheckBox();
        RBflavour4 = new javax.swing.JCheckBox();
        RBflavour6 = new javax.swing.JCheckBox();
        sosPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        exitSos = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        RBsos1 = new javax.swing.JRadioButton();
        RBsos2 = new javax.swing.JRadioButton();
        RBsos3 = new javax.swing.JRadioButton();
        RBsos4 = new javax.swing.JRadioButton();
        cartPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cartLabel = new javax.swing.JLabel();
        clearCart = new javax.swing.JButton();
        addCart = new javax.swing.JButton();
        cart = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        viewCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subway Order System");
        setBackground(new java.awt.Color(32, 177, 74));
        setMinimumSize(new java.awt.Dimension(900, 650));

        backgroundColour.setBackground(new java.awt.Color(32, 177, 74));
        backgroundColour.setLayout(null);

        buttonDone.setBackground(new java.awt.Color(255, 255, 255));
        buttonDone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonDone.setText("Proceed To Payment");
        buttonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoneActionPerformed(evt);
            }
        });
        backgroundColour.add(buttonDone);
        buttonDone.setBounds(630, 550, 160, 25);

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        backgroundColour.add(cancel);
        cancel.setBounds(50, 550, 75, 25);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssuuub.jpg"))); // NOI18N
        backgroundColour.add(title);
        title.setBounds(330, 0, 220, 60);

        panelSelection.setBackground(new java.awt.Color(255, 255, 51));
        panelSelection.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        panelSelection.setLayout(null);

        size.setBackground(new java.awt.Color(255, 255, 255));
        size.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        size.setText("Size");
        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });
        panelSelection.add(size);
        size.setBounds(20, 40, 90, 25);

        bread.setBackground(new java.awt.Color(255, 255, 255));
        bread.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bread.setText("Bread");
        bread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadActionPerformed(evt);
            }
        });
        panelSelection.add(bread);
        bread.setBounds(20, 110, 90, 25);

        flavour.setBackground(new java.awt.Color(255, 255, 255));
        flavour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        flavour.setText("Flavour");
        flavour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flavourActionPerformed(evt);
            }
        });
        panelSelection.add(flavour);
        flavour.setBounds(20, 180, 90, 25);

        veggie.setBackground(new java.awt.Color(255, 255, 255));
        veggie.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        veggie.setText("Veggie");
        veggie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggieActionPerformed(evt);
            }
        });
        panelSelection.add(veggie);
        veggie.setBounds(20, 250, 90, 25);

        sos.setBackground(new java.awt.Color(255, 255, 255));
        sos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sos.setText("Sauce");
        sos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosActionPerformed(evt);
            }
        });
        panelSelection.add(sos);
        sos.setBounds(20, 320, 90, 25);

        addon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addon.setText("Add ons");
        addon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addonActionPerformed(evt);
            }
        });
        panelSelection.add(addon);
        addon.setBounds(20, 390, 90, 25);

        backgroundColour.add(panelSelection);
        panelSelection.setBounds(20, 70, 130, 460);

        panelMenu.setBackground(new java.awt.Color(32, 177, 74));
        panelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51)));
        panelMenu.setLayout(new java.awt.CardLayout());

        veggiePanel.setBackground(new java.awt.Color(32, 177, 74));
        veggiePanel.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onion.jpg"))); // NOI18N
        veggiePanel.add(jLabel13);
        jLabel13.setBounds(380, 40, 220, 90);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tomato.png"))); // NOI18N
        veggiePanel.add(jLabel12);
        jLabel12.setBounds(10, 40, 220, 90);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cucumber.jpg"))); // NOI18N
        veggiePanel.add(jLabel14);
        jLabel14.setBounds(10, 160, 220, 90);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green peppers.jpg"))); // NOI18N
        veggiePanel.add(jLabel15);
        jLabel15.setBounds(360, 150, 220, 100);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/olive.jpg"))); // NOI18N
        veggiePanel.add(jLabel16);
        jLabel16.setBounds(10, 300, 230, 100);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lettuce230x110.jpg"))); // NOI18N
        veggiePanel.add(jLabel17);
        jLabel17.setBounds(360, 300, 230, 110);

        exitVegie.setBackground(new java.awt.Color(255, 255, 255));
        exitVegie.setForeground(new java.awt.Color(255, 51, 51));
        exitVegie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonX.png"))); // NOI18N
        exitVegie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitVegieActionPerformed(evt);
            }
        });
        veggiePanel.add(exitVegie);
        exitVegie.setBounds(640, 10, 50, 50);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel36.setText("Please select vegetable that you want.");
        veggiePanel.add(jLabel36);
        jLabel36.setBounds(10, 10, 240, 17);

        RBveggie1.setBackground(new java.awt.Color(32, 177, 74));
        RBveggie1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBveggie1.setText("Tomato");
        veggiePanel.add(RBveggie1);
        RBveggie1.setBounds(30, 130, 130, 25);

        RBveggie2.setBackground(new java.awt.Color(32, 177, 74));
        RBveggie2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBveggie2.setText("Onion");
        veggiePanel.add(RBveggie2);
        RBveggie2.setBounds(390, 130, 130, 25);

        RBveggie3.setBackground(new java.awt.Color(32, 177, 74));
        RBveggie3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBveggie3.setText("Cucumber");
        veggiePanel.add(RBveggie3);
        RBveggie3.setBounds(30, 260, 130, 25);

        RBveggie4.setBackground(new java.awt.Color(32, 177, 74));
        RBveggie4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBveggie4.setText("Green Pepper");
        veggiePanel.add(RBveggie4);
        RBveggie4.setBounds(390, 260, 130, 25);

        RBveggie5.setBackground(new java.awt.Color(32, 177, 74));
        RBveggie5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBveggie5.setText("Olive");
        veggiePanel.add(RBveggie5);
        RBveggie5.setBounds(30, 410, 130, 25);

        RBveggie6.setBackground(new java.awt.Color(32, 177, 74));
        RBveggie6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBveggie6.setText("Lettuce");
        veggiePanel.add(RBveggie6);
        RBveggie6.setBounds(390, 410, 130, 25);

        panelMenu.add(veggiePanel, "card2");

        sizePanel.setBackground(new java.awt.Color(32, 177, 74));
        sizePanel.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/footlong.jpg"))); // NOI18N
        sizePanel.add(jLabel1);
        jLabel1.setBounds(370, 160, 250, 60);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6inch.jpg"))); // NOI18N
        sizePanel.add(jLabel22);
        jLabel22.setBounds(50, 150, 200, 90);

        exitSize.setBackground(new java.awt.Color(255, 255, 255));
        exitSize.setForeground(new java.awt.Color(255, 51, 51));
        exitSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonX.png"))); // NOI18N
        exitSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitSizeActionPerformed(evt);
            }
        });
        sizePanel.add(exitSize);
        exitSize.setBounds(640, 10, 50, 50);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("Please select size that you want. Make it footlong for only RM 14.90");
        sizePanel.add(jLabel33);
        jLabel33.setBounds(10, 10, 430, 30);

        RBsize1.setBackground(new java.awt.Color(32, 177, 74));
        RBsize1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBsize1.setText("<html>6 Inch<br>RM10.90</html>");
        RBsize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBsize1ActionPerformed(evt);
            }
        });
        sizePanel.add(RBsize1);
        RBsize1.setBounds(90, 260, 100, 40);

        RBsize2.setBackground(new java.awt.Color(32, 177, 74));
        RBsize2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBsize2.setText("<html>12 Inch<br>+RM4.00</html>");
        RBsize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBsize2ActionPerformed(evt);
            }
        });
        sizePanel.add(RBsize2);
        RBsize2.setBounds(430, 260, 100, 40);

        panelMenu.add(sizePanel, "card3");

        breadPanel.setBackground(new java.awt.Color(32, 177, 74));
        breadPanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bread_wheat.png"))); // NOI18N
        breadPanel.add(jLabel2);
        jLabel2.setBounds(30, 40, 230, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/honey oat.jpg"))); // NOI18N
        breadPanel.add(jLabel3);
        jLabel3.setBounds(380, 50, 220, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ItalianBreadLoaf.jpg"))); // NOI18N
        breadPanel.add(jLabel4);
        jLabel4.setBounds(30, 220, 240, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parmesan.png"))); // NOI18N
        breadPanel.add(jLabel5);
        jLabel5.setBounds(390, 240, 230, 90);

        exitBread.setBackground(new java.awt.Color(255, 255, 255));
        exitBread.setForeground(new java.awt.Color(255, 51, 51));
        exitBread.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonX.png"))); // NOI18N
        exitBread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBreadActionPerformed(evt);
            }
        });
        breadPanel.add(exitBread);
        exitBread.setBounds(640, 10, 50, 50);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setText("Please select bread that you want.");
        breadPanel.add(jLabel34);
        jLabel34.setBounds(20, 10, 240, 17);

        RBbread1.setBackground(new java.awt.Color(32, 177, 74));
        RBbread1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBbread1.setText("Wheat");
        RBbread1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbread1ActionPerformed(evt);
            }
        });
        breadPanel.add(RBbread1);
        RBbread1.setBounds(50, 170, 160, 25);

        RBbread2.setBackground(new java.awt.Color(32, 177, 74));
        RBbread2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBbread2.setText("Honey Oat");
        RBbread2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbread2ActionPerformed(evt);
            }
        });
        breadPanel.add(RBbread2);
        RBbread2.setBounds(400, 170, 160, 25);

        RBbread3.setBackground(new java.awt.Color(32, 177, 74));
        RBbread3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBbread3.setText("Italian Bread Loaf");
        RBbread3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbread3ActionPerformed(evt);
            }
        });
        breadPanel.add(RBbread3);
        RBbread3.setBounds(50, 330, 160, 25);

        RBbread4.setBackground(new java.awt.Color(32, 177, 74));
        RBbread4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBbread4.setText("Parmesan");
        RBbread4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbread4ActionPerformed(evt);
            }
        });
        breadPanel.add(RBbread4);
        RBbread4.setBounds(400, 330, 160, 25);

        panelMenu.add(breadPanel, "card4");

        addonPanel.setBackground(new java.awt.Color(32, 177, 74));
        addonPanel.setLayout(null);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Set 1.jpg"))); // NOI18N
        addonPanel.add(jLabel23);
        jLabel23.setBounds(170, 50, 110, 130);

        RBaddon4.setBackground(new java.awt.Color(32, 177, 74));
        RBaddon4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBaddon4.setText("<html>Set 4<br>+RM2.00</html>");
        RBaddon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBaddon4ActionPerformed(evt);
            }
        });
        addonPanel.add(RBaddon4);
        RBaddon4.setBounds(310, 350, 120, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Set 4.jpg"))); // NOI18N
        addonPanel.add(jLabel26);
        jLabel26.setBounds(290, 230, 90, 130);

        RBaddon3.setBackground(new java.awt.Color(32, 177, 74));
        RBaddon3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBaddon3.setText("<html>Set 3<br>+RM2.00</html>");
        RBaddon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBaddon3ActionPerformed(evt);
            }
        });
        addonPanel.add(RBaddon3);
        RBaddon3.setBounds(70, 350, 120, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Set 3.jpg"))); // NOI18N
        addonPanel.add(jLabel25);
        jLabel25.setBounds(60, 230, 110, 130);

        exitAddon.setBackground(new java.awt.Color(255, 255, 255));
        exitAddon.setForeground(new java.awt.Color(255, 51, 51));
        exitAddon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonX.png"))); // NOI18N
        exitAddon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAddonActionPerformed(evt);
            }
        });
        addonPanel.add(exitAddon);
        exitAddon.setBounds(646, 11, 50, 50);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Set 2.jpg"))); // NOI18N
        addonPanel.add(jLabel31);
        jLabel31.setBounds(410, 50, 110, 130);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        addonPanel.add(jLabel32);
        jLabel32.setBounds(490, 220, 130, 150);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel38.setText("Make it a meal with only add more RM2.00.");
        addonPanel.add(jLabel38);
        jLabel38.setBounds(10, 10, 280, 17);

        RBaddon1.setBackground(new java.awt.Color(32, 177, 74));
        RBaddon1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBaddon1.setText("<html>Set 1<br>+RM2.00</html>");
        RBaddon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBaddon1ActionPerformed(evt);
            }
        });
        addonPanel.add(RBaddon1);
        RBaddon1.setBounds(180, 170, 120, 60);

        RBaddon2.setBackground(new java.awt.Color(32, 177, 74));
        RBaddon2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBaddon2.setText("<html>Set 2<br>+RM2.00</html>");
        RBaddon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBaddon2ActionPerformed(evt);
            }
        });
        addonPanel.add(RBaddon2);
        RBaddon2.setBounds(430, 180, 120, 40);

        RBaddon5.setBackground(new java.awt.Color(32, 177, 74));
        RBaddon5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBaddon5.setText("Ala Carte");
        RBaddon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBaddon5ActionPerformed(evt);
            }
        });
        addonPanel.add(RBaddon5);
        RBaddon5.setBounds(510, 360, 120, 25);

        panelMenu.add(addonPanel, "card8");

        flavourPanel.setBackground(new java.awt.Color(32, 177, 74));
        flavourPanel.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("Please select flavour that you want.");
        flavourPanel.add(jLabel35);
        jLabel35.setBounds(10, 10, 250, 17);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chicken Slice.jpg"))); // NOI18N
        flavourPanel.add(jLabel6);
        jLabel6.setBounds(20, 20, 230, 110);

        RBflavour2.setBackground(new java.awt.Color(32, 177, 74));
        RBflavour2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBflavour2.setText("<html>Roast Beef<br>+RM2.00</html>");
        RBflavour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBflavour2ActionPerformed(evt);
            }
        });
        flavourPanel.add(RBflavour2);
        RBflavour2.setBounds(400, 120, 140, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roast Beef.jpg"))); // NOI18N
        flavourPanel.add(jLabel7);
        jLabel7.setBounds(380, 20, 220, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Steak & Cheese.jpg"))); // NOI18N
        flavourPanel.add(jLabel8);
        jLabel8.setBounds(20, 160, 230, 100);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tuna.jpg"))); // NOI18N
        flavourPanel.add(jLabel9);
        jLabel9.setBounds(370, 160, 220, 110);

        RBflavour5.setBackground(new java.awt.Color(32, 177, 74));
        RBflavour5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBflavour5.setText("<html>Turkey Breast<br>+RM2.00</html>");
        RBflavour5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBflavour5ActionPerformed(evt);
            }
        });
        flavourPanel.add(RBflavour5);
        RBflavour5.setBounds(30, 400, 140, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Turkey Breast.jpg"))); // NOI18N
        flavourPanel.add(jLabel10);
        jLabel10.setBounds(20, 300, 220, 110);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Veggie Delite.jpg"))); // NOI18N
        flavourPanel.add(jLabel11);
        jLabel11.setBounds(380, 300, 230, 110);

        exitFlavour.setBackground(new java.awt.Color(255, 255, 255));
        exitFlavour.setForeground(new java.awt.Color(255, 51, 51));
        exitFlavour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonX.png"))); // NOI18N
        exitFlavour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFlavourActionPerformed(evt);
            }
        });
        flavourPanel.add(exitFlavour);
        exitFlavour.setBounds(640, 10, 50, 50);

        RBflavour1.setBackground(new java.awt.Color(32, 177, 74));
        RBflavour1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBflavour1.setText("Chicken Slice");
        RBflavour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBflavour1ActionPerformed(evt);
            }
        });
        flavourPanel.add(RBflavour1);
        RBflavour1.setBounds(30, 130, 140, 25);

        RBflavour3.setBackground(new java.awt.Color(32, 177, 74));
        RBflavour3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBflavour3.setText("Steak & Cheese");
        RBflavour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBflavour3ActionPerformed(evt);
            }
        });
        flavourPanel.add(RBflavour3);
        RBflavour3.setBounds(30, 270, 140, 25);

        RBflavour4.setBackground(new java.awt.Color(32, 177, 74));
        RBflavour4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBflavour4.setText("Tuna");
        RBflavour4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBflavour4ActionPerformed(evt);
            }
        });
        flavourPanel.add(RBflavour4);
        RBflavour4.setBounds(400, 270, 140, 25);

        RBflavour6.setBackground(new java.awt.Color(32, 177, 74));
        RBflavour6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBflavour6.setText("Veggie Delite");
        RBflavour6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBflavour6ActionPerformed(evt);
            }
        });
        flavourPanel.add(RBflavour6);
        RBflavour6.setBounds(400, 410, 140, 25);

        panelMenu.add(flavourPanel, "card5");

        sosPanel.setBackground(new java.awt.Color(32, 177, 74));
        sosPanel.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cili.png"))); // NOI18N
        sosPanel.add(jLabel18);
        jLabel18.setBounds(30, 70, 160, 110);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayonis.jpg"))); // NOI18N
        sosPanel.add(jLabel19);
        jLabel19.setBounds(360, 60, 190, 130);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tomato.jpg"))); // NOI18N
        sosPanel.add(jLabel20);
        jLabel20.setBounds(80, 250, 100, 110);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thousandIsland.jpg"))); // NOI18N
        sosPanel.add(jLabel21);
        jLabel21.setBounds(370, 240, 170, 130);

        exitSos.setBackground(new java.awt.Color(255, 255, 255));
        exitSos.setForeground(new java.awt.Color(255, 51, 51));
        exitSos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonX.png"))); // NOI18N
        exitSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitSosActionPerformed(evt);
            }
        });
        sosPanel.add(exitSos);
        exitSos.setBounds(640, 10, 50, 50);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("Please select sauce that you want.");
        sosPanel.add(jLabel37);
        jLabel37.setBounds(10, 10, 220, 17);

        RBsos1.setBackground(new java.awt.Color(32, 177, 74));
        RBsos1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBsos1.setText("Chili Sauce");
        sosPanel.add(RBsos1);
        RBsos1.setBounds(90, 190, 120, 25);

        RBsos2.setBackground(new java.awt.Color(32, 177, 74));
        RBsos2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBsos2.setText("Mayonnaise");
        sosPanel.add(RBsos2);
        RBsos2.setBounds(420, 190, 120, 25);

        RBsos3.setBackground(new java.awt.Color(32, 177, 74));
        RBsos3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBsos3.setText("Ketchup");
        sosPanel.add(RBsos3);
        RBsos3.setBounds(90, 370, 120, 25);

        RBsos4.setBackground(new java.awt.Color(32, 177, 74));
        RBsos4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RBsos4.setText("Thousand Island");
        sosPanel.add(RBsos4);
        RBsos4.setBounds(420, 370, 140, 25);

        panelMenu.add(sosPanel, "card6");

        cartPanel.setBackground(new java.awt.Color(32, 177, 74));
        cartPanel.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonX.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        cartPanel.add(jButton1);
        jButton1.setBounds(640, 10, 50, 50);

        cartLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cartPanel.add(cartLabel);
        cartLabel.setBounds(10, 40, 530, 320);

        panelMenu.add(cartPanel, "card8");

        backgroundColour.add(panelMenu);
        panelMenu.setBounds(170, 70, 710, 460);

        clearCart.setBackground(new java.awt.Color(255, 255, 255));
        clearCart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearCart.setText("Clear Cart");
        clearCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCartActionPerformed(evt);
            }
        });
        backgroundColour.add(clearCart);
        clearCart.setBounds(400, 550, 110, 25);

        addCart.setBackground(new java.awt.Color(255, 255, 255));
        addCart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addCart.setText("Add Cart");
        addCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCartActionPerformed(evt);
            }
        });
        backgroundColour.add(addCart);
        addCart.setBounds(420, 550, 90, 25);

        cart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backgroundColour.add(cart);
        cart.setBounds(230, 550, 180, 30);

        instruction.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backgroundColour.add(instruction);
        instruction.setBounds(170, 70, 630, 40);

        viewCart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewCart.setText("View Cart");
        viewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartActionPerformed(evt);
            }
        });
        backgroundColour.add(viewCart);
        viewCart.setBounds(520, 550, 100, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundColour, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundColour, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setPicture() // Initialize picture for each meals.
    {    
        for(int i = 0; i<countCart; i++)
        {
            if(addonSelection[i].equals("Set 1"))
            {            
                pictureTop[i] = new ImageIcon(getClass().getResource("/Set 1.jpg"));              
            }
            else if(Order.addonSelection[i].equals("Set 2"))
            {            
                pictureTop[i] = new ImageIcon(getClass().getResource("/Set 2.jpg"));              
            }
            else if(Order.addonSelection[i].equals("Set 3"))
            {
                pictureTop[i] = new ImageIcon(getClass().getResource("/Set 3.jpg"));              
            }
            else if(Order.addonSelection[i].equals("Set 4"))
            {
                pictureTop[i] = new ImageIcon(getClass().getResource("/Set 4.jpg"));              
            }
            if(Order.flavourSelection[i].equals("Chicken Slice"))
            {
                pictureBottom[i] = new ImageIcon(getClass().getResource("/Chicken Slice.jpg"));              
            }
            else if(Order.flavourSelection[i].equals("Roast Beef"))
            {
                pictureBottom[i] = new ImageIcon(getClass().getResource("/Roast Beef.jpg"));              
            }
            else if(Order.flavourSelection[i].equals("Steak & Cheese"))
            {
                pictureBottom[i] = new ImageIcon(getClass().getResource("/Steak & Cheese.jpg"));              
            }
            else if(Order.flavourSelection[i].equals("Tuna"))
            {
                pictureBottom[i] = new ImageIcon(getClass().getResource("/Tuna.jpg"));              
            }
            else if(Order.flavourSelection[i].equals("Turkey Breast"))
            {
                pictureBottom[i] = new ImageIcon(getClass().getResource("/Turkey Breast.jpg"));              
            }
            else if(Order.flavourSelection[i].equals("Veggie Delite"))
            {
                pictureBottom[i] = new ImageIcon(getClass().getResource("/Veggie Delite.jpg"));              
            }
        }        
    }
    public void setPrice() // Initialize price.
    {        
        for(int i = 0; i<countCart; i++)
        {            
            if(flavourSelection[i].equals("Chicken Slice"))
            {
                if(sizeSelection[i].equals("6 Inch"))
                {
                    price[i] = 10.90;
                }
                else if(sizeSelection[i].equals("12 Inch"))
                {
                    price[i] = 14.90;
                }            
            }
            else if(flavourSelection[i].equals("Roast Beef"))
            {
                if(sizeSelection[i].equals("6 Inch"))
                {
                    price[i] = 12.90;
                }
                else if(sizeSelection[i].equals("12 Inch"))
                {
                    price[i] = 16.90;
                }
            }
            else if(flavourSelection[i].equals("Steak & Cheese"))
            {
                if(sizeSelection[i].equals("6 Inch"))
                {
                    price[i] = 10.90;
                }
                else if(sizeSelection[i].equals("12 Inch"))
                {
                    price[i] = 14.90;
                }
            }
            else if(flavourSelection[i].equals("Tuna"))
            {
                if(sizeSelection[i].equals("6 Inch"))
                {
                    price[i] = 10.90;
                }
                else if(sizeSelection[i].equals("12 Inch"))
                {
                    price[i] = 14.90;
                }
            }
            else if(flavourSelection[i].equals("Turkey Breast"))
            {
                if(sizeSelection[i].equals("6 Inch"))
                {
                    price[i] = 12.90;
                }
                else if(sizeSelection[i].equals("12 Inch"))
                {
                    price[i] = 16.90;
                }
            }
            else if(flavourSelection[i].equals("Veggie Delite"))
            {
                if(sizeSelection[i].equals("6 Inch"))
                {
                    price[i] = 10.90;
                }
                else if(sizeSelection[i].equals("12 Inch"))
                {
                    price[i] = 14.90;
                }
            }
            if(addonSelection[i].equals("Set 1") || addonSelection[i].equals("Set 2") || addonSelection[i].equals("Set 3") || addonSelection[i].equals("Set 4")) // If user take set.
            {
                price[i] = price[i] + 2.00;
            }
        }        
    }
    public String print() // Concat string for output.
    {
        String str = "<html>In my cart: <br><br>";
        for(int i = 0; i<countCart; i++)
        {
            str = str  + sizeSelection[i] +" - " + breadSelection[i] + " - " +flavourSelection[i] + " - " + addonSelection[i] + " - RM" + df.format(price[i]) + "<br>";
        }       
        str = str + "</html>";
        return str;
    }
    public void defaultInstruction() // Instruction for user.
    {
        instruction.setText("<html>Instruction:<br>Please select at least one item in each parts(Size, Bread, Flavour, Add ons)</html>");
    }
    public void allVarInit() // Initialize all variable.
    {        
        countCart = 0;
        for(int i = 0; i<sizeSelection.length; i++)
        {
            sizeSelection[i] = null;
        }
        for(int i = 0; i<breadSelection.length; i++)
        {
            breadSelection[i] = null;
        }
        for(int i = 0; i<flavourSelection.length; i++)
        {
            flavourSelection[i] = null;
        }
        for(int i = 0; i<addonSelection.length; i++)
        {
            addonSelection[i] = null;
        }   
        for(int i = 0; i<price.length; i++)
        {
            price[i] = 0;
        }
        for(int i = 0; i<pictureTop.length; i++)
        {
            pictureTop[i] = null;
        }
        for(int i = 0; i<pictureBottom.length; i++)
        {
            pictureBottom[i] = null;
        }
    }
    public void closeMenu() // Closing panel on interface.
    {
        panelMenu.setVisible(false);
        breadPanel.setVisible(false);
        flavourPanel.setVisible(false);
        veggiePanel.setVisible(false);
        sosPanel.setVisible(false);
        sizePanel.setVisible(false);
        addonPanel.setVisible(false);
        cartPanel.setVisible(false);
    }
    public void icon() // Interface
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/S.jpeg")));
    }
    private void sizeSelectedFalse() // Interface
    {
        RBsize1.setSelected(false);
        RBsize2.setSelected(false);
    }
    private void breadSelectedFalse() // Interface
    {
        RBbread1.setSelected(false);
        RBbread2.setSelected(false);
        RBbread3.setSelected(false);
        RBbread4.setSelected(false);
    }
    private void flavourSelectedFalse() // Interface
    {
        RBflavour1.setSelected(false);
        RBflavour2.setSelected(false);
        RBflavour3.setSelected(false);
        RBflavour4.setSelected(false);
        RBflavour5.setSelected(false);
        RBflavour6.setSelected(false);
    }
    private void veggieSelectedFalse() // Interface
    {
        RBveggie1.setSelected(false);
        RBveggie2.setSelected(false);
        RBveggie3.setSelected(false);
        RBveggie4.setSelected(false);
        RBveggie5.setSelected(false);
        RBveggie6.setSelected(false);
    }
    private void sauceSelectedFalse() // Interface
    {
        RBsos1.setSelected(false);
        RBsos2.setSelected(false);
        RBsos3.setSelected(false);
        RBsos4.setSelected(false);        
    }
    private void addonSelectedFalse() // Interface
    {
        RBaddon1.setSelected(false);
        RBaddon2.setSelected(false);
        RBaddon3.setSelected(false);
        RBaddon4.setSelected(false);
        RBaddon5.setSelected(false);
    }
    public void printCart() // Print in my cart.
    {
        cartLabel.setText(print());
    }
    private void addCart() // Add selected item to cart.
    {   
        if(RBsize1.isSelected())
            sizeSelection[countCart] = "6 Inch";                           
        if(RBsize2.isSelected())
            sizeSelection[countCart] = "12 Inch";
        if(RBbread1.isSelected())
            breadSelection[countCart] = "Wheat"; 
        if(RBbread2.isSelected())
            breadSelection[countCart] = "Honey Oat"; 
        if(RBbread3.isSelected())
            breadSelection[countCart] = "Italian Bread Loaf"; 
        if(RBbread4.isSelected())
            breadSelection[countCart] = "Parmesan"; 
        if(RBflavour1.isSelected())
            flavourSelection[countCart] = "Chicken Slice"; 
        if(RBflavour2.isSelected())
            flavourSelection[countCart] = "Roast Beef"; 
        if(RBflavour3.isSelected())
            flavourSelection[countCart] = "Steak & Cheese"; 
        if(RBflavour4.isSelected())
            flavourSelection[countCart] = "Tuna"; 
        if(RBflavour5.isSelected())
            flavourSelection[countCart] = "Turkey Breast"; 
        if(RBflavour6.isSelected())
            flavourSelection[countCart] = "Veggie Delite"; 
        if(RBaddon1.isSelected()) 
            addonSelection[countCart] = "Set 1";
        if(RBaddon2.isSelected()) 
            addonSelection[countCart] = "Set 2";
        if(RBaddon3.isSelected()) 
            addonSelection[countCart] = "Set 3";
        if(RBaddon4.isSelected()) 
            addonSelection[countCart] = "Set 4";
        if(RBaddon5.isSelected()) 
            addonSelection[countCart] = "Ala Carte";               
        check();               
    }   
    public void check() //To check whether the user has pick on every part
    {        
        if(sizeSelection[countCart]!=null && breadSelection[countCart]!=null && flavourSelection[countCart]!=null && addonSelection[countCart]!=null)
        {                  
            countCart++;
            cart.setText("Item(s) in cart: "+countCart);
            defaultInstruction();            
        }
        else if(sizeSelection[countCart] == null || breadSelection[countCart] == null || flavourSelection[countCart] == null || addonSelection[countCart] == null)
        {
            closeMenu();
            instruction.setText("<html>Warning:<br>You have not selected all type of parts. Please select all type of parts before proceed</html>");
        }
        if(countCart>=1)
        {
            buttonDone.setVisible(true);
            viewCart.setVisible(true);
        }
    }
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        allVarInit();
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void buttonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoneActionPerformed
        setPicture();
        setPrice();
        new Receipt().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonDoneActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
        closeMenu();
        clearCart.setVisible(false);
        panelMenu.setVisible(true);                
        sizePanel.setVisible(true);
    }//GEN-LAST:event_sizeActionPerformed

    private void breadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadActionPerformed
        closeMenu();
        clearCart.setVisible(false);
        panelMenu.setVisible(true); 
        breadPanel.setVisible(true);
    }//GEN-LAST:event_breadActionPerformed

    private void flavourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flavourActionPerformed
        closeMenu();
        clearCart.setVisible(false);
        panelMenu.setVisible(true);
        flavourPanel.setVisible(true);
    }//GEN-LAST:event_flavourActionPerformed

    private void veggieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggieActionPerformed
        closeMenu();
        clearCart.setVisible(false);
        panelMenu.setVisible(true);
        veggiePanel.setVisible(true);
    }//GEN-LAST:event_veggieActionPerformed

    private void sosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosActionPerformed
        closeMenu();
        clearCart.setVisible(false);
        panelMenu.setVisible(true);
        sosPanel.setVisible(true);
    }//GEN-LAST:event_sosActionPerformed

    private void exitFlavourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFlavourActionPerformed
        closeMenu();
    }//GEN-LAST:event_exitFlavourActionPerformed

    private void exitBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBreadActionPerformed
        closeMenu();
    }//GEN-LAST:event_exitBreadActionPerformed

    private void exitSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitSizeActionPerformed
        closeMenu();
    }//GEN-LAST:event_exitSizeActionPerformed

    private void exitVegieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitVegieActionPerformed
        closeMenu();
    }//GEN-LAST:event_exitVegieActionPerformed

    private void addonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addonActionPerformed
        closeMenu();
        clearCart.setVisible(false);
        panelMenu.setVisible(true);
        addonPanel.setVisible(true);
    }//GEN-LAST:event_addonActionPerformed

    private void exitSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitSosActionPerformed
        closeMenu();
    }//GEN-LAST:event_exitSosActionPerformed

    private void exitAddonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAddonActionPerformed
        closeMenu();
    }//GEN-LAST:event_exitAddonActionPerformed

    private void addCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCartActionPerformed
       addCart();        
       sizeSelectedFalse();
       breadSelectedFalse();
       flavourSelectedFalse();
       veggieSelectedFalse();
       sauceSelectedFalse();
       addonSelectedFalse();
       closeMenu();
    }//GEN-LAST:event_addCartActionPerformed

    private void RBsize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBsize1ActionPerformed
        sizeSelectedFalse();
        RBsize1.setSelected(true);
    }//GEN-LAST:event_RBsize1ActionPerformed

    private void RBsize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBsize2ActionPerformed
        sizeSelectedFalse();
        RBsize2.setSelected(true);
    }//GEN-LAST:event_RBsize2ActionPerformed

    private void RBbread1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbread1ActionPerformed
        breadSelectedFalse();
        RBbread1.setSelected(true);
    }//GEN-LAST:event_RBbread1ActionPerformed

    private void RBbread2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbread2ActionPerformed
        breadSelectedFalse();
        RBbread2.setSelected(true);
    }//GEN-LAST:event_RBbread2ActionPerformed

    private void RBbread3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbread3ActionPerformed
        breadSelectedFalse();
        RBbread3.setSelected(true);
    }//GEN-LAST:event_RBbread3ActionPerformed

    private void RBbread4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbread4ActionPerformed
        breadSelectedFalse();
        RBbread4.setSelected(true);
    }//GEN-LAST:event_RBbread4ActionPerformed

    private void RBflavour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBflavour1ActionPerformed
        flavourSelectedFalse();
        RBflavour1.setSelected(true);
    }//GEN-LAST:event_RBflavour1ActionPerformed

    private void RBflavour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBflavour2ActionPerformed
        flavourSelectedFalse();
        RBflavour2.setSelected(true);
    }//GEN-LAST:event_RBflavour2ActionPerformed

    private void RBflavour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBflavour3ActionPerformed
        flavourSelectedFalse();
        RBflavour3.setSelected(true);
    }//GEN-LAST:event_RBflavour3ActionPerformed

    private void RBflavour4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBflavour4ActionPerformed
        flavourSelectedFalse();
        RBflavour4.setSelected(true);
    }//GEN-LAST:event_RBflavour4ActionPerformed

    private void RBflavour5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBflavour5ActionPerformed
        flavourSelectedFalse();
        RBflavour5.setSelected(true);
    }//GEN-LAST:event_RBflavour5ActionPerformed

    private void RBflavour6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBflavour6ActionPerformed
        flavourSelectedFalse();
        RBflavour6.setSelected(true);
    }//GEN-LAST:event_RBflavour6ActionPerformed

    private void viewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartActionPerformed
        closeMenu();
        panelMenu.setVisible(true);
        cartPanel.setVisible(true);  
        clearCart.setVisible(true);
        setPrice();
        printCart();
    }//GEN-LAST:event_viewCartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        closeMenu();
        clearCart.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RBaddon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBaddon1ActionPerformed
        addonSelectedFalse();
        RBaddon1.setSelected(true);
    }//GEN-LAST:event_RBaddon1ActionPerformed

    private void RBaddon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBaddon2ActionPerformed
        addonSelectedFalse();
        RBaddon2.setSelected(true);
    }//GEN-LAST:event_RBaddon2ActionPerformed

    private void RBaddon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBaddon3ActionPerformed
        addonSelectedFalse();
        RBaddon3.setSelected(true);
    }//GEN-LAST:event_RBaddon3ActionPerformed

    private void RBaddon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBaddon4ActionPerformed
        addonSelectedFalse();
        RBaddon4.setSelected(true);
    }//GEN-LAST:event_RBaddon4ActionPerformed

    private void RBaddon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBaddon5ActionPerformed
        addonSelectedFalse();
        RBaddon5.setSelected(true);
    }//GEN-LAST:event_RBaddon5ActionPerformed

    private void clearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCartActionPerformed
        allVarInit();
        closeMenu();
        countCart = 0;
        cart.setText("Item(s) in cart: "+countCart);
        buttonDone.setVisible(false); 
        viewCart.setVisible(false);
        clearCart.setVisible(false);
    }//GEN-LAST:event_clearCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox RBaddon1;
    private javax.swing.JCheckBox RBaddon2;
    private javax.swing.JCheckBox RBaddon3;
    private javax.swing.JCheckBox RBaddon4;
    private javax.swing.JCheckBox RBaddon5;
    private javax.swing.JCheckBox RBbread1;
    private javax.swing.JCheckBox RBbread2;
    private javax.swing.JCheckBox RBbread3;
    private javax.swing.JCheckBox RBbread4;
    private javax.swing.JCheckBox RBflavour1;
    private javax.swing.JCheckBox RBflavour2;
    private javax.swing.JCheckBox RBflavour3;
    private javax.swing.JCheckBox RBflavour4;
    private javax.swing.JCheckBox RBflavour5;
    private javax.swing.JCheckBox RBflavour6;
    private javax.swing.JCheckBox RBsize1;
    private javax.swing.JCheckBox RBsize2;
    private javax.swing.JRadioButton RBsos1;
    private javax.swing.JRadioButton RBsos2;
    private javax.swing.JRadioButton RBsos3;
    private javax.swing.JRadioButton RBsos4;
    private javax.swing.JRadioButton RBveggie1;
    private javax.swing.JRadioButton RBveggie2;
    private javax.swing.JRadioButton RBveggie3;
    private javax.swing.JRadioButton RBveggie4;
    private javax.swing.JRadioButton RBveggie5;
    private javax.swing.JRadioButton RBveggie6;
    private javax.swing.JButton addCart;
    private javax.swing.JButton addon;
    private javax.swing.JPanel addonPanel;
    private javax.swing.JPanel backgroundColour;
    private javax.swing.JButton bread;
    private javax.swing.JPanel breadPanel;
    private javax.swing.JButton buttonDone;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel cart;
    private javax.swing.JLabel cartLabel;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JButton clearCart;
    private javax.swing.JButton exitAddon;
    private javax.swing.JButton exitBread;
    private javax.swing.JButton exitFlavour;
    private javax.swing.JButton exitSize;
    private javax.swing.JButton exitSos;
    private javax.swing.JButton exitVegie;
    private javax.swing.JButton flavour;
    private javax.swing.JPanel flavourPanel;
    private javax.swing.JLabel instruction;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSelection;
    private javax.swing.JButton size;
    private javax.swing.JPanel sizePanel;
    private javax.swing.JButton sos;
    private javax.swing.JPanel sosPanel;
    private javax.swing.JLabel title;
    private javax.swing.JButton veggie;
    private javax.swing.JPanel veggiePanel;
    private javax.swing.JButton viewCart;
    // End of variables declaration//GEN-END:variables
}