import java.awt.Toolkit;
import java.text.DecimalFormat;

public class Receipt extends javax.swing.JFrame {

    DecimalFormat df = new DecimalFormat("0.00");      
    double subTotal = 0, grandTotal = 0;
    String picLabel;
    int page = 0;
    public Receipt() {
        initComponents();
        icon();     
        printReceipt();        
        setGambar(page);           
    }    
    public void icon() // Interface.
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/S.png")));
    }  
    public void printReceipt() // Print receipt.
    {
        jTextArea1.setText(print()+printSubTotal()+printGrandTotal());
    }
    public String print() // Concat string.
    {
        String print = "";        
        for(int i = 0; i<Order.countCart; i++)
        {
            print = print+ Order.sizeSelection[i] + " - " + Order.breadSelection[i] + " - " + Order.flavourSelection[i] + " - " +  Order.addonSelection[i] + " - RM" + df.format(Order.price[i]) + "\n";
        }       
        return print;
    }
    public String printSubTotal() // Return subTotal.
    {
        for(int i = 0; i<Order.countCart; i++)
        {
            subTotal = subTotal + Order.price[i];
        }        
        return "\nSub total: "+df.format(subTotal)+"\n";
    }
    public String printGrandTotal() // Return tax and grandTotal.
    {
        double tax = subTotal * 0.06;
        grandTotal = subTotal * 1.06; //GST
        return "Tax: "+ df.format(tax)+"\n\nGrand total: "+ df.format(grandTotal);
    }
    public void setGambar(int i) // Display image.
    {   
        buttonLeft.setVisible(true);
        buttonRight.setVisible(true);
        if(i <= 0)
            buttonLeft.setVisible(false);
        if(i >= (Order.countCart - 1))
            buttonRight.setVisible(false);        
        gambarAtas.setIcon(null);
        gambarBawah.setIcon(null);        
        picLabel = null;
        picLabel = Order.flavourSelection[i] + " - " + Order.addonSelection[i];
        label.setText(picLabel);
        gambarAtas.setIcon(Order.pictureTop[i]);
        gambarBawah.setIcon(Order.pictureBottom[i]);     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        panelReceipt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        panelGambar = new javax.swing.JPanel();
        gambarAtas = new javax.swing.JLabel();
        gambarBawah = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        buttonLeft = new javax.swing.JButton();
        buttonRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subway Order System");
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(32, 177, 74));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel1.setText("Receipt");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(370, 10, 133, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 30, 900, 60);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttonHome.png"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(20, 530, 50, 50);

        buttonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttonX.png"))); // NOI18N
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        jPanel1.add(buttonExit);
        buttonExit.setBounds(830, 530, 50, 50);

        panelReceipt.setBackground(new java.awt.Color(0, 153, 51));
        panelReceipt.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 51)));

        jTextArea1.setBackground(new java.awt.Color(0, 153, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(20);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Subway Official Receipt");

        javax.swing.GroupLayout panelReceiptLayout = new javax.swing.GroupLayout(panelReceipt);
        panelReceipt.setLayout(panelReceiptLayout);
        panelReceiptLayout.setHorizontalGroup(
            panelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelReceiptLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        panelReceiptLayout.setVerticalGroup(
            panelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReceiptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelReceipt);
        panelReceipt.setBounds(360, 140, 430, 380);

        panelGambar.setBackground(new java.awt.Color(32, 177, 74));
        panelGambar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 51)));
        panelGambar.setLayout(null);
        panelGambar.add(gambarAtas);
        gambarAtas.setBounds(3, 3, 254, 200);
        panelGambar.add(gambarBawah);
        gambarBawah.setBounds(10, 204, 240, 170);

        label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panelGambar.add(label);
        label.setBounds(10, 10, 240, 30);

        jPanel1.add(panelGambar);
        panelGambar.setBounds(60, 140, 260, 380);

        buttonLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttonLeft.png"))); // NOI18N
        buttonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeftActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLeft);
        buttonLeft.setBounds(130, 530, 50, 50);

        buttonRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttonRight.png"))); // NOI18N
        buttonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRightActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRight);
        buttonRight.setBounds(190, 530, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void buttonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeftActionPerformed
        if(page > 0)
        {
            page--;            
        }                
        setGambar(page);
    }//GEN-LAST:event_buttonLeftActionPerformed

    private void buttonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRightActionPerformed
        if(page < Order.countCart)
        {
            page++;            
        }                
        setGambar(page);
    }//GEN-LAST:event_buttonRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLeft;
    private javax.swing.JButton buttonRight;
    private static javax.swing.JLabel gambarAtas;
    private static javax.swing.JLabel gambarBawah;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label;
    private javax.swing.JPanel panelGambar;
    private javax.swing.JPanel panelReceipt;
    // End of variables declaration//GEN-END:variables
}
